my:
  greeting: Hello World from the RocknRoll Album-Service
spring:
  application:
  datasource:
#     url: "jdbc:mysql://rocknroll-microservices-v3_default:3306/album-inventory-service"
    url: "jdbc:mysql://rnr-mysql:3307/album-inventory-service"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'secret'
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 0
springdoc:
  swagger-ui:
    path: "http://swagger-ui.html"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://rnr-eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: 'true'
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            nodeValue: TRACE
    root: INFO
