my:
  greeting: Hello World from the Album-Service
spring:
  application:
  datasource:
    url: "jdbc:mysql://localhost:3306/album-inventory-service"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'password'
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 0
springdoc:
  swagger-ui:
    path: "http://swagger-ui.html"
