eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekawhale:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
msg: greeting Hello World from the RocknRoll Album-Service configwhale
